### PR TITLE
Fixed docstring in Algorithm.py to indicate that I1 must be intrafocal and I2 must be extrafocal.

### PR DESCRIPTION
**Pull request by jfcrenshaw**
I thought about renaming I1 and I2 to more descriptive names (e.g. intraImg, extraImg), but didn't want to introduce backwards-incompatibility. Let me know if you think that change would be preferred.

### CODE REVIEW

**Comment by teweitsai** [comment]
For the variable names, I prefer to put the common parts first such as `imgIntra` and `imgExtra`. By doing this, when you are using the IDE or Jupiter notebook, you can use the `tab`+`tab` (or other shortcut) to find the available terms more quickly.

**Comment by jfcrenshaw** [comment]
That makes sense. Are you saying you want me to change `I1` and `I2` to `imgIntra` and `imgExtra`?

**Comment by teweitsai** [comment]
No. The `I1` + `I2` or `imgIntra` + `imgExtra` works to me. I just mean the naming convention of variables. Sorry to mislead you. Thanks!

**Comment by jbkalmbach** [comment]
Looks fine to me. If you do want to change to `imgIntra` and `imgExtra` I would support that. I don't think it will break anything since it seems these `I1` and `I2` calls are all limited to within the functions of `Algorithm.py`.

You'll need to rebase and update your `doc/versionHistory.rst`.

**Review by jbkalmbach — APPROVED** [review]
Looks fine to me. If you do want to change to imgIntra and imgExtra I would support that. I don't think it will break anything since it seems these I1 and I2 calls are all limited to within the functions of Algorithm.py.

You'll need to rebase and update your doc/versionHistory.rst.

**Comment by jfcrenshaw** [comment]
Rather than changing this documentation, I believe the I1/I2 symmetry can be restored by fixing the mask rotations in the algorithm. Once that gets sorted out, I will check if the symmetry is restored, and either close or merge this PR, depending on the results of that test.

**Pull request closed without merging**
