### PR TITLE
Added link to the docs

### PR DESCRIPTION
**Pull request by jfcrenshaw**
I added a link to the docs to the top of the README

### CODE REVIEW

**Comment by jbkalmbach** [comment]
Maybe we could use a button to be more visible?

For instance something like this:
https://img.shields.io/badge/docs-ts__wep.lsst.io-brightgreen

**Comment by jfcrenshaw** [comment]
@jbkalmbach I added the badge. I think it's not a bad idea to leave the link in the text as well, but let me know if you think I should remove it.

**Comment by jfcrenshaw** [comment]
Note that whoever owns the repo can also add the link to the docs to the Github repo's "About" panel at the top-right of the homepage. E.g. see the [PZFlow repo](https://github.com/jfcrenshaw/pzflow):
image

**Comment by jbkalmbach** [comment]
Can you update the file [doc/versionHistory](https://github.com/lsst-ts/ts_wep/blob/develop/doc/versionHistory.rst)?

**Comment by jbkalmbach** [comment]
Also I just merged something else so make sure to do a rebase.

**Review by jbkalmbach — APPROVED** [review]
Looks good. Thanks for the update!

**Pull request merged**
